CREATE TABLE IF NOT EXISTS 'current_weather'.'main' (
 'id' INT(11) NOT NULL AUTO_INCREMENT,
 'temp' DOUBLE NULL DEFAULT NULL,
 'humidity' INT(11) NULL DEFAULT NULL, 
 'pressure' INT(11) NULL DEFAULT NULL,
 'temp_min' DOUBLE NULL DEFAULT NULL,
 'temp_max` DOUBLE NULL DEFAULT NULL,
 'sea_level' DOUBLE NULL DEFAULT NULL, 
 'grnd_level' DOUBLE NULL DEFAULT NULL,
 PRIMARY KEY ('id')) ENGINE = InnoDB AUTO_INCREMENT = 2 DEFAULT CHARACTER SET = utf8
 